workflows:
  ios-release:
    name: iOS Release InsuBuddy
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Build Web App
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install
      - name: Build IPA
        scripts:
      - name: Install Dependencies
        script: npm install
      - name: Build Web App
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install
      - name: Fetch Profiles (Neu)
        script: xcode-project use-profiles # Holt Zertifikate von Apple ab
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --mode release \
            --generate-export-options-plist
    publishing:
      app_store_connect:
        auth: integration
    integrations:
      app_store_connect: "InsuBuddy Connect"