import React, { createContext, useContext, useState } from 'react';

export const CURRENCIES = [
  { code: 'CHF', symbol: 'CHF', flag: '🇨🇭', name: 'Swiss Franc' },
  { code: 'EUR', symbol: '€',   flag: '🇪🇺', name: 'Euro' },
  { code: 'USD', symbol: '$',   flag: '🇺🇸', name: 'US Dollar' },
  { code: 'GBP', symbol: '£',   flag: '🇬🇧', name: 'British Pound' },
  { code: 'JPY', symbol: '¥',   flag: '🇯🇵', name: 'Japanese Yen' },
  { code: 'CAD', symbol: 'CA$', flag: '🇨🇦', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$',  flag: '🇦🇺', name: 'Australian Dollar' },
];

const TRANSLATIONS = {
  de: {
    // Login
    welcome_back: 'Willkommen zurück!',
    login_subtitle: 'Melde dich bei deinem InsuBuddy-Konto an',
    email: 'E-Mail',
    password: 'Passwort',
    forgot_password: 'Passwort vergessen?',
    login_btn: 'Anmelden',
    no_account: 'Noch kein Konto?',
    register_link: 'Jetzt registrieren',
    login_error: 'Anmeldung fehlgeschlagen',
    reset_sent: 'Passwort-Reset E-Mail gesendet!',
    // Register
    create_account: 'Konto erstellen',
    register_subtitle: 'Starte deine smarte Versicherungsverwaltung',
    confirm_password: 'Passwort bestätigen',
    password_mismatch: 'Passwörter stimmen nicht überein',
    password_too_short: 'Passwort muss mindestens 6 Zeichen lang sein',
    register_btn: 'Konto erstellen',
    already_account: 'Bereits ein Konto?',
    login_link: 'Anmelden',
    register_error: 'Registrierung fehlgeschlagen',
    confirm_sent: 'Bestätigungsmail gesendet! Bitte überprüfe deine E-Mails.',
    referral_placeholder: 'Empfehlungscode (optional)',
    // Dashboard tabs
    tab_overview: 'Übersicht',
    tab_policies: 'Policen',
    tab_vault: 'Tresor',
    tab_finances: 'Finanzen',
    tab_advisors: 'Berater',
    tab_chat: 'KI-Chat',
    tab_profile: 'Profil',
    // Dashboard general
    active_policies: 'Aktive Policen',
    secured_values: 'Gesicherte Werte',
    recommendations: 'Empfehlungen',
    action_required: 'Handlungsbedarf',
    policy_overview: 'Policen-Übersicht',
    annual_premium: 'Jährliche Gesamtprämie',
    check_needed: 'Prüfung nötig',
    optimal: 'Optimal',
    coverage: 'Deckung',
    premium: 'Prämie',
    digital_vault: 'Digitaler Tresor',
    secured_values_proof: 'Gesicherte Werte mit Nachweis',
    language: 'Sprache',
    currency: 'Währung',
    cancel: 'Abbrechen',
    save: 'Speichern',
    mark_all_read: 'Alle als gelesen',
    no_notifications: 'Keine Benachrichtigungen',
    household: 'Hausrat',
    car: 'Auto',
    liability: 'Haftpflicht',
    health: 'Krankenkasse',
    filter_all: 'Alle',
    filter_warning: 'Warnungen',
    filter_reminder: 'Erinnerungen',
    filter_info: 'Info',
    export_data: 'Daten exportieren',
    export_policies: 'Policen PDF',
    export_vault: 'Tresor Excel',
    export_all: 'Alles',
    scan_receipt: 'Beleg scannen',
    qr_scanner: 'QR-Scanner',
    scan_instruction: 'QR-Code positionieren',
    biometric_auth: 'Biometrie',
    biometric_desc: 'Face ID aktivieren',
    biometric_setup_title: 'Biometrie einrichten',
    biometric_setup_desc: 'Mit Face ID schützen',
    setup_now: 'Jetzt einrichten',
    add_policy: 'Police hinzufügen',
    upload_policy_pdf: 'Police hochladen',
    select_pdf: 'PDF auswählen',
    or_drag_drop: 'oder hierher ziehen',
    policy_name: 'Policen-Name',
    policy_company: 'Versicherung',
    policy_type: 'Typ',
    select_type: 'Typ auswählen',
    notifications: 'Benachrichtigungen',
    notif_policy_update: 'Hausrat anpassen',
    notif_document_uploaded: 'Dokument hochgeladen',
    notif_savings_found: '420 Sparpotenzial',
    notif_renewal_reminder: 'Auto läuft ab',
    app_title: 'InsuBuddy',
    app_subtitle: 'Ihr intelligenter Lebenslagen-Navigator',
    // Dashboard overview
    with_pdf: 'Mit PDF',
    expiring_soon: 'Laufen bald ab',
    expiring_policies: '⚠️ Ablaufende Policen',
    expires_in_days: 'Läuft in',
    days_suffix: 'Tagen ab',
    renew_now: 'Jetzt verlängern',
    your_insurances: 'Deine Versicherungen',
    annual_costs: 'Jährliche Kosten',
    per_month: 'Pro Monat',
    active_policies_label: 'Aktive Policen',
    documented: 'Dokumentiert',
    monthly_premium_overview: '💳 Monatliche Prämien-Übersicht',
    total_per_month: 'Total pro Monat',
    coverage_radar: 'Deckungslücken-Radar',
    coverage_radar_sub: 'Wie gut bist du abgesichert?',
    of: 'von',
    covered_label: 'abgedeckt',
    well_covered: 'Gut abgesichert!',
    well_covered_sub: 'Du hast alle wichtigen Versicherungen abgedeckt.',
    covered_tag: 'ABGEDECKT',
    life_event_checker: 'Lebensereignis-Checker',
    life_event_sub: 'Was steht bei dir an?',
    checklist: 'Checkliste',
    already_covered: 'Bereits abgedeckt',
    not_yet: 'Noch nicht vorhanden',
    contact_advisor: 'Berater kontaktieren',
    recommended_insurances: '🎯 Empfohlene Versicherungen',
    partner_offers: 'Ausgewählte Partner-Angebote für Sie',
    view_offer: 'Angebot ansehen',
    view_all: 'Alle ansehen',
    no_policies: 'Noch keine Policen hinzugefügt',
    show_coverages: 'Deckungen anzeigen',
    view_pdf: 'PDF ansehen',
    cancel_policy: 'Kündigen',
    delete_policy: 'Löschen',
    coverages_label: 'Deckungen',
    // Priority labels
    priority_pflicht: 'Pflicht',
    priority_sehr_empfohlen: 'Sehr empfohlen',
    priority_empfohlen: 'Empfohlen',
    priority_situativ: 'Situativ',
    priority_optional: 'Optional',
    // Life events
    le_umzug: 'Umzug',
    le_heirat: 'Heirat',
    le_kind: 'Kind',
    le_auto: 'Auto',
    le_hauskauf: 'Hauskauf',
    le_scheidung: 'Scheidung',
    le_pension: 'Pension',
    le_selbstaendig: 'Selbständig',
    // Vault tab
    secured_items: 'Wertgegenstände gesichert',
    add_item: 'Wertgegenstand hinzufügen',
    no_items: 'Noch keine Wertgegenstände hinzugefügt',
    no_items_sub: 'Dokumentieren Sie Ihre wertvollen Gegenstände mit Foto',
    item_purchased: 'Gekauft:',
    // Advisors tab
    advisors_title: 'Empfohlene Berater',
    advisors_sub: 'Finde den passenden Versicherungsberater in deiner Nähe',
    no_advisors: 'Noch keine Berater verfügbar',
    no_advisors_sub: 'Berater werden bald hinzugefügt.',
    // Profile tab
    profile_user: 'InsuBuddy Nutzer',
    expiry_reminders: 'Ablauf-Erinnerungen',
    expiry_reminders_sub: 'Benachrichtigungen über ablaufende Policen',
    notify_before: 'Benachrichtigung',
    days_before_expiry: 'Tage vor Ablauf',
    account_settings_btn: 'Konto-Einstellungen',
    logout: 'Abmelden',
    // Chat
    chat_title: 'KI-Versicherungsassistent',
    // Export modal
    export_modal_title: 'Policen PDFs exportieren',
    no_pdfs: 'Keine PDFs vorhanden',
    no_pdfs_sub: 'Laden Sie zuerst Policen-PDFs hoch',
    download: 'Herunterladen',
    close: 'Schliessen',
    // Add policy modal
    annual_premium_field: 'Jährliche Prämie',
    expiry_date_field: 'Ablaufdatum (optional)',
    what_covered: 'Was ist gedeckt? (Optional)',
    saving: 'Wird gespeichert...',
    // Add item modal
    add_item_title: 'Wertgegenstand hinzufügen',
    item_name_label: 'Name des Gegenstands',
    item_value_label: 'Wert',
    item_category_label: 'Kategorie',
    item_purchase_date_label: 'Kaufdatum (optional)',
    item_photo_label: 'Foto/Quittung',
    // Support
    new_ticket: 'Neues Ticket',
    ticket_submit_btn: 'Ticket absenden',
    support_reply: 'Antwort vom Support:',
    // Invite
    invite_friends: 'Freunde einladen',
    invite_friends_sub: 'Teile InsuBuddy mit deinen Freunden',
    personal_link: 'Dein persönlicher Link',
  },
  en: {
    // Login
    welcome_back: 'Welcome back!',
    login_subtitle: 'Sign in to your InsuBuddy account',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot password?',
    login_btn: 'Sign In',
    no_account: 'No account yet?',
    register_link: 'Register now',
    login_error: 'Login failed',
    reset_sent: 'Password reset email sent!',
    // Register
    create_account: 'Create Account',
    register_subtitle: 'Start your smart insurance management',
    confirm_password: 'Confirm Password',
    password_mismatch: 'Passwords do not match',
    password_too_short: 'Password must be at least 6 characters',
    register_btn: 'Create Account',
    already_account: 'Already have an account?',
    login_link: 'Sign In',
    register_error: 'Registration failed',
    confirm_sent: 'Confirmation email sent! Please check your inbox.',
    referral_placeholder: 'Referral code (optional)',
    // Dashboard tabs
    tab_overview: 'Overview',
    tab_policies: 'Policies',
    tab_vault: 'Vault',
    tab_finances: 'Finances',
    tab_advisors: 'Advisors',
    tab_chat: 'AI Chat',
    tab_profile: 'Profile',
    // Dashboard general
    active_policies: 'Active Policies',
    secured_values: 'Secured Values',
    recommendations: 'Recommendations',
    action_required: 'Action Required',
    policy_overview: 'Policy Overview',
    annual_premium: 'Annual Premium',
    check_needed: 'Check Needed',
    optimal: 'Optimal',
    coverage: 'Coverage',
    premium: 'Premium',
    digital_vault: 'Digital Vault',
    secured_values_proof: 'Secured Values with Proof',
    language: 'Language',
    currency: 'Currency',
    cancel: 'Cancel',
    save: 'Save',
    mark_all_read: 'Mark all read',
    no_notifications: 'No notifications',
    household: 'Household',
    car: 'Car',
    liability: 'Liability',
    health: 'Health',
    filter_all: 'All',
    filter_warning: 'Warnings',
    filter_reminder: 'Reminders',
    filter_info: 'Info',
    export_data: 'Export Data',
    export_policies: 'Policies PDF',
    export_vault: 'Vault Excel',
    export_all: 'All',
    scan_receipt: 'Scan Receipt',
    qr_scanner: 'QR Scanner',
    scan_instruction: 'Position QR code',
    biometric_auth: 'Biometric',
    biometric_desc: 'Enable Face ID',
    biometric_setup_title: 'Setup Biometric',
    biometric_setup_desc: 'Protect with Face ID',
    setup_now: 'Setup Now',
    add_policy: 'Add Policy',
    upload_policy_pdf: 'Upload Policy',
    select_pdf: 'Select PDF',
    or_drag_drop: 'or drag here',
    policy_name: 'Policy Name',
    policy_company: 'Company',
    policy_type: 'Type',
    select_type: 'Select type',
    notifications: 'Notifications',
    notif_policy_update: 'Update household insurance',
    notif_document_uploaded: 'Document uploaded',
    notif_savings_found: '420 savings potential',
    notif_renewal_reminder: 'Car expires soon',
    app_title: 'InsuBuddy',
    app_subtitle: 'Your intelligent insurance navigator',
    // Dashboard overview
    with_pdf: 'With PDF',
    expiring_soon: 'Expiring soon',
    expiring_policies: '⚠️ Expiring Policies',
    expires_in_days: 'Expires in',
    days_suffix: 'days',
    renew_now: 'Renew now',
    your_insurances: 'Your Insurance',
    annual_costs: 'Annual Costs',
    per_month: 'Per Month',
    active_policies_label: 'Active Policies',
    documented: 'Documented',
    monthly_premium_overview: '💳 Monthly Premium Overview',
    total_per_month: 'Total per month',
    coverage_radar: 'Coverage Gap Radar',
    coverage_radar_sub: 'How well are you covered?',
    of: 'of',
    covered_label: 'covered',
    well_covered: 'Well covered!',
    well_covered_sub: 'You have all important insurances covered.',
    covered_tag: 'COVERED',
    life_event_checker: 'Life Event Checker',
    life_event_sub: "What's coming up for you?",
    checklist: 'Checklist',
    already_covered: 'Already covered',
    not_yet: 'Not yet available',
    contact_advisor: 'Contact advisor',
    recommended_insurances: '🎯 Recommended Insurances',
    partner_offers: 'Selected partner offers for you',
    view_offer: 'View offer',
    view_all: 'View all',
    no_policies: 'No policies added yet',
    show_coverages: 'Show coverages',
    view_pdf: 'View PDF',
    cancel_policy: 'Cancel',
    delete_policy: 'Delete',
    coverages_label: 'Coverages',
    // Priority labels
    priority_pflicht: 'Mandatory',
    priority_sehr_empfohlen: 'Highly recommended',
    priority_empfohlen: 'Recommended',
    priority_situativ: 'Situational',
    priority_optional: 'Optional',
    // Life events
    le_umzug: 'Moving',
    le_heirat: 'Marriage',
    le_kind: 'Child',
    le_auto: 'Car',
    le_hauskauf: 'Home purchase',
    le_scheidung: 'Divorce',
    le_pension: 'Retirement',
    le_selbstaendig: 'Self-employed',
    // Vault tab
    secured_items: 'valuable items secured',
    add_item: 'Add valuable item',
    no_items: 'No valuable items added yet',
    no_items_sub: 'Document your valuable items with a photo',
    item_purchased: 'Purchased:',
    // Advisors tab
    advisors_title: 'Recommended Advisors',
    advisors_sub: 'Find the right insurance advisor near you',
    no_advisors: 'No advisors available yet',
    no_advisors_sub: 'Advisors will be added soon.',
    // Profile tab
    profile_user: 'InsuBuddy User',
    expiry_reminders: 'Expiry Reminders',
    expiry_reminders_sub: 'Notifications about expiring policies',
    notify_before: 'Notify',
    days_before_expiry: 'days before expiry',
    account_settings_btn: 'Account Settings',
    logout: 'Sign Out',
    // Chat
    chat_title: 'AI Insurance Assistant',
    // Export modal
    export_modal_title: 'Export Policy PDFs',
    no_pdfs: 'No PDFs available',
    no_pdfs_sub: 'Upload policy PDFs first',
    download: 'Download',
    close: 'Close',
    // Add policy modal
    annual_premium_field: 'Annual Premium',
    expiry_date_field: 'Expiry date (optional)',
    what_covered: 'What is covered? (Optional)',
    saving: 'Saving...',
    // Add item modal
    add_item_title: 'Add valuable item',
    item_name_label: 'Item name',
    item_value_label: 'Value',
    item_category_label: 'Category',
    item_purchase_date_label: 'Purchase date (optional)',
    item_photo_label: 'Photo/Receipt',
    // Support
    new_ticket: 'New ticket',
    ticket_submit_btn: 'Submit ticket',
    support_reply: 'Reply from support:',
    // Invite
    invite_friends: 'Invite Friends',
    invite_friends_sub: 'Share InsuBuddy with your friends',
    personal_link: 'Your personal link',
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem('insubuddy_language') || 'de'
  );
  const [currency, setCurrencyState] = useState(
    () => localStorage.getItem('insubuddy_currency') || 'CHF'
  );

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('insubuddy_language', lang);
  };

  const setCurrency = (cur) => {
    setCurrencyState(cur);
    localStorage.setItem('insubuddy_currency', cur);
  };

  const t = (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS['de'][key] || key;

  const currencyInfo = CURRENCIES.find(c => c.code === currency) || CURRENCIES[0];

  return (
    <LanguageContext.Provider value={{
      language, setLanguage,
      currency, setCurrency,
      currencySymbol: currencyInfo.symbol,
      currencyInfo,
      t,
      CURRENCIES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
